apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: kubia
  labels:
    app: kubia
spec:
  # modify replicas according to your case
  replicas: 3
   selector:
 matchExpressions:
 - key: app
 operator: In
 values:
 - kubia 
  template:
    metadata:
      labels:
        app: kubia
    spec:
      containers:
        - name: kubia
          image: luksa/kubia
#same as the other replicaset and rc but this one is more expressive app=kubia is a must
#both need to be present not only one!!