apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: kubia
  labels:
    app: kubia
spec:
  # modify replicas according to your case
  replicas: 3
  selector:
    matchLabels:
      app: kubia
  template:
    metadata:
      labels:
        app: kubia
    spec:
      containers:
        - name: kubia
          image: luksa/kubia
