apiVersion: v1
kind: Service
metadata:
  name: kubia-nodeport1
spec:
  type: NodePort
  selector:
    app: kubia
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8088
      nodePort: 30122
