apiVersion: v1
kind: Pod
metadata:
  name: kubia-manual-2
spec:
  containers:
    - name: kubia
      image: luksa/kubia
      ports:
        - name: kubia
          containerPort: 8080
          protocol: TCP
